---
heat_template_version: 2017-02-24
description: "O-RAN Simulator Dummy Heat"
parameters:
    vnf_name:
      type: string
      description: VNF Name (provided by ONAP)
    vnf_id:
      type: string
      description: VNF ID (provided by ONAP)
    vf_module_id:
      type: string
      description: VF Module ID (provided by ONAP)
    skip_post_instantiation_configuration:
      type: boolean
      default: false
    sdnc_model_name:
        type: string
        default: a1_pe_simulator
    sdnc_model_version:
        type: string
        default: 1.3.2
    sdnc_artifact_name:
        type: string
        default: vnf
    controller_actor:
      type: string
      default: CDS
resources:
    dummy_node:
        type: OS::Nova::Server
        properties:
            name: dummy
            image: dummy
            flavor: dummy
